# Generated by Django 4.0.5 on 2022-11-01 00:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leadgen', '0002_rename_todo_lead'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lead',
            name='user',
        ),
    ]
