# Generated by Django 4.0.5 on 2022-11-03 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leadgen', '0003_remove_lead_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='address',
            field=models.CharField(blank=True, choices=[('Calabasas', 'Calabasas'), ('Thousand Oaks', 'Thousand Oaks'), ('Beverky hills', 'Beverky hills')], max_length=100),
        ),
    ]
