# Generated by Django 4.0.5 on 2023-01-26 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leadgen', '0006_lead_customer_email_lead_customer_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='detail_4',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='lead',
            name='detail_5',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='lead',
            name='detail_6',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='lead',
            name='detail_7',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
