# Generated by Django 4.0.5 on 2023-01-26 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leadgen', '0008_alter_lead_detail_1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='detail_1',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
