# Generated by Django 4.0.5 on 2023-01-27 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leadgen', '0010_alter_lead_detail_1_alter_lead_detail_2_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lead',
            old_name='time_span',
            new_name='urgency',
        ),
        migrations.AddField(
            model_name='lead',
            name='customer_phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='lead',
            name='ready_to_hire',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='lead',
            name='street',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
