# Generated by Django 4.0.5 on 2023-01-27 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leadgen', '0011_rename_time_span_lead_urgency_lead_customer_phone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='custome_user_input',
            field=models.CharField(blank=True, max_length=2000),
        ),
    ]
